### PR TITLE
Requirements.txt: Using Pyrogram Asyncio Version

### PR DESCRIPTION
**Pull request by tomyprs25**

### CODE REVIEW

**Comment by tomyprs25** [comment]
**Here For Sure**: 

``Traceback (most recent call last):
  File "string_session.py", line 37, in <module>
    asyncio.get_event_loop().run_until_complete(generateStringSession())
  File "/data/data/com.termux/files/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "string_session.py", line 24, in generateStringSession
    async with Client(
AttributeError: __aexit__``

**Comment by rzlamrr** [comment]
@tomyprs25 Anjay

**Comment by tomyprs25** [comment]
@rzlamrr Dah gak sabar , pen make bishproject full async

**Comment by MoveAngel** [comment]
@tomyprs25 AWOAKOWKAOWK

**Comment by tomyprs25** [comment]
@MoveAngel Qmack

**Comment by tomyprs25** [comment]
@MoveAngel When -_ One4pyro

**Comment by fadlyas07** [comment]
halo salam kenal

**Comment by tomyprs25** [comment]
@fadlyas07 Fadlijon

**Comment by MoveAngel** [comment]
@tomyprs25 https://github.com/MoveAngel/SkyDX caming son

**Comment by rzlamrr** [comment]
@tomyprs25 Ramenyaaaa

**Comment by fadlyas07** [comment]
burung gelatik burung puyuh

**Comment by terrorgrid87** [comment]
@fadlyas07 HALOAPAKABAR? RAWE RAWE LANTAS MALANG MALANG TUNTAS!

**Comment by rzlamrr** [comment]
Ngopi ler wkwkwkk

**Comment by tomyprs25** [comment]
@fadlyas07 Bapak kao gak iso nguyuh

**Comment by fadlyas07** [comment]
kuy nge gay epribadeh

**Comment by rzlamrr** [comment]
@fadlyas07 Sama @tomyprs25 sana, cocok kalian tu

**Comment by tomyprs25** [comment]
@rzlamrr Gusti salah ku opo :(

**Comment by fadlyas07** [comment]
@tomyprs25

**Comment by tomyprs25** [comment]
@fadlyas07 Apa ler , ngapain stay di githyby

**Comment by rzlamrr** [comment]
@fadlyas07 👍

**Comment by rzlamrr** [comment]
@tomyprs25 👉👌💦

**Comment by MoveAngel** [comment]
dahan bala bala

**Comment by tomyprs25** [comment]
@MoveAngel Botmu gak bisa join grup

**Comment by MoveAngel** [comment]
@tomyprs25 Private

**Pull request closed without merging**
